import {
  User,
  AuthenticationDetail,
  RevokedToken,
  Resource,
  ResourceComputedView,
  ResourceUsage,
  ResourceIntroduction,
  ResourceIntroductionUser,
  ResourceIntroductionHistoryItem,
  MqttServer,
  MqttResourceConfig,
  WebhookConfig,
  SSOProvider,
  SSOProviderOIDCConfiguration,
  ResourceGroup,
} from '@attraccess/database-entities';

export const entities = {
  User,
  AuthenticationDetail,
  RevokedToken,
  Resource,
  ResourceComputedView,
  ResourceUsage,
  ResourceIntroduction,
  ResourceIntroductionUser,
  ResourceIntroductionHistoryItem,
  MqttServer,
  MqttResourceConfig,
  WebhookConfig,
  SSOProvider,
  SSOProviderOIDCConfiguration,
  ResourceGroup,
};
